-- PaySim Payment Gateway — Oracle SQL Schema
-- This file represents the "Oracle format" of the database for educational purposes.
-- The application uses TypeORM to manage these tables automatically.

-- 1. Customers Table
CREATE TABLE "customers" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" VARCHAR2(36) NOT NULL,
    "first_name" VARCHAR2(100) NOT NULL,
    "last_name" VARCHAR2(100) NOT NULL,
    "email" VARCHAR2(255) UNIQUE NOT NULL,
    "phone" VARCHAR2(20),
    "password_hash" VARCHAR2(255) NOT NULL,
    "pin_hash" VARCHAR2(255),
    "status" VARCHAR2(20) DEFAULT 'active',
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Merchants Table
CREATE TABLE "merchants" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" VARCHAR2(36) NOT NULL,
    "business_name" VARCHAR2(255) NOT NULL,
    "business_email" VARCHAR2(255) UNIQUE NOT NULL,
    "phone" VARCHAR2(20),
    "password_hash" VARCHAR2(255) NOT NULL,
    "status" VARCHAR2(20) DEFAULT 'active',
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Wallets Table
CREATE TABLE "wallets" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "customer_id" NUMBER NOT NULL,
    "wallet_id" VARCHAR2(36) NOT NULL,
    "balance" NUMBER(18, 2) DEFAULT 0.00,
    "currency" VARCHAR2(3) DEFAULT 'INR',
    "status" VARCHAR2(20) DEFAULT 'active',
    CONSTRAINT fk_wallet_customer FOREIGN KEY ("customer_id") REFERENCES "customers"("id")
);

-- 4. Credit Cards Table
CREATE TABLE "credit_cards" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "customer_id" NUMBER NOT NULL,
    "card_number_hash" VARCHAR2(255) NOT NULL,
    "card_last_four" VARCHAR2(4) NOT NULL,
    "card_brand" VARCHAR2(20),
    "credit_limit" NUMBER(18, 2),
    "used_credit" NUMBER(18, 2) DEFAULT 0.00,
    "status" VARCHAR2(20) DEFAULT 'active',
    CONSTRAINT fk_card_customer FOREIGN KEY ("customer_id") REFERENCES "customers"("id")
);

-- 5. Transactions Table
CREATE TABLE "transactions" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "txn_id" VARCHAR2(36) NOT NULL,
    "customer_id" NUMBER NOT NULL,
    "merchant_id" NUMBER NOT NULL,
    "amount" NUMBER(18, 2) NOT NULL,
    "currency" VARCHAR2(3) NOT NULL,
    "status" VARCHAR2(20) NOT NULL,
    "mode" VARCHAR2(20) NOT NULL,
    "verified_at" TIMESTAMP,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_txn_customer FOREIGN KEY ("customer_id") REFERENCES "customers"("id"),
    CONSTRAINT fk_txn_merchant FOREIGN KEY ("merchant_id") REFERENCES "merchants"("id")
);

-- Note: This is a simplified subset of the full schema. 
-- See docs/DATABASE_SCHEMA.md for the full architecture.
